[formatter.statix]
command = "sh"
options = ["-euc", "for file in \"$@\"; do statix check \"$file\"; done"]
includes = [ "*.nix" ]
priority = 1

[formatter.nixpkgs-fmt]
command = "nixpkgs-fmt"
includes = ["*.nix"]
priority = 3