# Hardware detection for framey (Framework 13 AMD 7040).
# Disk layout is managed by disko.nix — do NOT add fileSystems or swapDevices here.
# Generated by nixos-generate-config, stripped to remove conflicts with disko-managed mounts.
{ config, lib, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "kvm-amd" "tpm_crb" "tpm_tis" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
